"""adiciona_coluna_accepted_terms_em_users

Revision ID: 456b9921f5e0
Revises: 41bb2bc3c6a5
Create Date: 2026-05-21 16:20:04.729497-04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456b9921f5e0'
down_revision: Union[str, None] = '41bb2bc3c6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('accepted_terms', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accepted_terms')
    # ### end Alembic commands ###
