"""Add author_email snapshot

Revision ID: cdb4339fac58
Revises: c45750ecec48
Create Date: 2026-06-20 06:43:34.875171-04:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cdb4339fac58"
down_revision: Union[str, None] = "c45750ecec48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column("author_email", sa.String(length=150), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "author_email")
    # ### end Alembic commands ###
