"""add hide_alternatives to exam_questions

Revision ID: 66faf0295d92
Revises: 6c53f228a6bb
Create Date: 2026-05-24 17:38:52.392742-04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66faf0295d92'
down_revision: Union[str, None] = '6c53f228a6bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_questions', sa.Column('hide_alternatives', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_questions', 'hide_alternatives')
    # ### end Alembic commands ###
