"""criar_custom_bncc

Revision ID: 6c53f228a6bb
Revises: 22270e629d98
Create Date: 2026-05-23 01:20:52.910539-04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c53f228a6bb'
down_revision: Union[str, None] = '22270e629d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_bncc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grauId', sa.Integer(), nullable=False),
    sa.Column('unidadeTematica', sa.String(), nullable=False),
    sa.Column('objetosDeConhecimento', sa.String(), nullable=False),
    sa.Column('habilidade', sa.String(), nullable=False),
    sa.Column('abilityDescription', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_bncc_habilidade'), 'custom_bncc', ['habilidade'], unique=True)
    op.create_index(op.f('ix_custom_bncc_id'), 'custom_bncc', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_bncc_id'), table_name='custom_bncc')
    op.drop_index(op.f('ix_custom_bncc_habilidade'), table_name='custom_bncc')
    op.drop_table('custom_bncc')
    # ### end Alembic commands ###
