"""add_user_profiles_table

Revision ID: a9a6de39f5e2
Revises: ab1890dcbb08
Create Date: 2026-05-18 03:20:49.194760-04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a6de39f5e2'
down_revision: Union[str, None] = 'ab1890dcbb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
