"""initial_schema

Revision ID: ab1890dcbb08
Revises: 3a965be443c6
Create Date: 2026-04-16 19:40:09.656040-04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1890dcbb08'
down_revision: Union[str, None] = '3a965be443c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('QUESTION_REVISED', 'EXAM_REVISED', 'QUESTION_APPROVED', 'QUESTION_COMMENTED', 'EXAM_COMMENTED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Enum('QUESTION', 'EXAM', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_entity_id'), 'notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_entity_type'), 'notifications', ['entity_type'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_triggered_by_user_id'), 'notifications', ['triggered_by_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('exams', sa.Column('ano', sa.Integer(), nullable=True))
    op.add_column('exams', sa.Column('header_image', sa.Text(), nullable=True))
    op.add_column('exams', sa.Column('footer_image', sa.Text(), nullable=True))
    op.add_column('exams', sa.Column('header_size', sa.Float(), nullable=False))
    op.add_column('exams', sa.Column('footer_size', sa.Float(), nullable=False))
    op.add_column('exams', sa.Column('reviewer_comments', sa.Text(), nullable=True))
    op.add_column('exams', sa.Column('author_name', sa.String(length=100), nullable=False))
    op.alter_column('exams', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('exams_author_id_fkey', 'exams', type_='foreignkey')
    op.create_foreign_key(None, 'exams', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.add_column('questions', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.alter_column('questions', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_questions_reviewed_by_id'), 'questions', ['reviewed_by_id'], unique=False)
    op.drop_constraint('questions_author_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'questions', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_author_id_fkey', 'questions', 'users', ['author_id'], ['id'])
    op.drop_index(op.f('ix_questions_reviewed_by_id'), table_name='questions')
    op.alter_column('questions', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('questions', 'reviewed_by_id')
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.create_foreign_key('exams_author_id_fkey', 'exams', 'users', ['author_id'], ['id'])
    op.alter_column('exams', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('exams', 'author_name')
    op.drop_column('exams', 'reviewer_comments')
    op.drop_column('exams', 'footer_size')
    op.drop_column('exams', 'header_size')
    op.drop_column('exams', 'footer_image')
    op.drop_column('exams', 'header_image')
    op.drop_column('exams', 'ano')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_triggered_by_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_entity_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_entity_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
