"""Add author_email to exams table

Revision ID: 2ce08d7570eb
Revises: cdb4339fac58
Create Date: 2026-06-20 07:12:41.620765-04:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2ce08d7570eb"
down_revision: Union[str, None] = "cdb4339fac58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exams",
        sa.Column("author_email", sa.String(length=150), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exams", "author_email")
    # ### end Alembic commands ###
