"""add reviewed_by_id to exams

Revision ID: c45750ecec48
Revises: 66faf0295d92
Create Date: 2026-05-26 04:42:05.778902-04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45750ecec48'
down_revision: Union[str, None] = '66faf0295d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exams', 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_column('exams', 'reviewed_by_id')
    # ### end Alembic commands ###
